language: php

php:
  - 5.6
  - 7
  - 7.1
  - 7.2

script:
 - composer install --prefer-source
 - ./vendor/bin/phpunit --coverage-clover=coverage.clover;

after_script:
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
